/// Generated by Sideko (sideko.dev)
#[derive(Clone, Debug)]
pub struct AiImageUpscalerClient {
    base_client: crate::core::base_client::BaseClient,
}
impl AiImageUpscalerClient {
    pub(crate) fn new(base_client: crate::core::base_client::BaseClient) -> Self {
        Self { base_client }
    }
    /// Upscale your image using AI. Each 2x upscale costs 50 frames, and 4x upscale costs 200 frames.
    pub async fn create(
        &self,
        request: super::request_types::CreateRequest,
    ) -> crate::SdkResult<crate::models::PostV1AiImageUpscalerResponse> {
        let url = self.base_client.build_url("/v1/ai-image-upscaler");
        let mut builder = reqwest::Client::default().post(&url);
        builder = builder.header("x-sideko-sdk-language", "rust");
        builder = builder.header("content-type", "application/json");
        builder = builder.json(&request.data);
        builder = self.base_client.apply_auths_to_builder(builder, &["bearerAuth"]);
        let mut response = builder.send().await?;
        response = self.base_client.error_for_status(response).await?;
        crate::core::response::process_json::<
            crate::models::PostV1AiImageUpscalerResponse,
        >(response)
            .await
    }
}
