/// Generated by Sideko (sideko.dev)
/// CreateRequest
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct CreateRequest {
    pub data: crate::models::PostV1TextToVideoBody,
}
