/// Generated by Sideko (sideko.dev)
#[derive(Clone, Debug)]
pub struct AnimationClient {
    base_client: crate::core::base_client::BaseClient,
}
impl AnimationClient {
    pub(crate) fn new(base_client: crate::core::base_client::BaseClient) -> Self {
        Self { base_client }
    }
    /// Create a Animation video. The estimated frame cost is calculated based on the `fps` and `end_seconds` input.
    ///
    /// POST /v1/animation
    pub async fn create(
        &self,
        request: super::request_types::CreateRequest,
    ) -> crate::SdkResult<crate::models::PostV1AnimationResponse> {
        let url = self.base_client.build_url("/v1/animation");
        let mut builder = reqwest::Client::default().post(&url);
        builder = builder.header("x-sideko-sdk-language", "rust");
        builder = builder.header("content-type", "application/json");
        builder = builder
            .json(
                &crate::models::PostV1AnimationBody {
                    name: request.name,
                    assets: request.assets,
                    end_seconds: request.end_seconds,
                    fps: request.fps,
                    height: request.height,
                    style: request.style,
                    width: request.width,
                },
            );
        builder = self.base_client.apply_auths_to_builder(builder, &["bearerAuth"]);
        let mut response = builder.send().await?;
        response = self.base_client.error_for_status(response).await?;
        crate::core::response::process_json::<
            crate::models::PostV1AnimationResponse,
        >(response)
            .await
    }
}
