/// Generated by Sideko (sideko.dev)
/// When a request fails validations
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct DeleteV1VideoProjectsIdResponse422 {
    pub message: String,
}
