/// Generated by Sideko (sideko.dev)
/// The request is not properly authenticated
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct DeleteV1ImageProjectsIdResponse401 {
    pub message: crate::models::DeleteV1ImageProjectsIdResponse401MessageEnum,
}
