/// Generated by Sideko (sideko.dev)
/// The request is not properly authenticated
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct DeleteV1VideoProjectsIdResponse401 {
    pub message: crate::models::DeleteV1VideoProjectsIdResponse401MessageEnum,
}
