/// Generated by Sideko (sideko.dev)
/// Requested resource is not found
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct DeleteV1VideoProjectsIdResponse404 {
    pub message: crate::models::DeleteV1VideoProjectsIdResponse404MessageEnum,
}
