/// Generated by Sideko (sideko.dev)
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct GetV1VideoProjectsIdResponse {
    pub created_at: String,
    #[serde(deserialize_with = "crate::core::patch::deserialize_required_nullable")]
    pub download: Option<crate::models::GetV1VideoProjectsIdResponseDownload>,
    pub end_seconds: f64,
    pub fps: f64,
    pub height: f64,
    pub id: String,
    #[serde(deserialize_with = "crate::core::patch::deserialize_required_nullable")]
    pub name: Option<String>,
    pub start_seconds: f64,
    pub status: crate::models::GetV1VideoProjectsIdResponseStatusEnum,
    pub total_frame_cost: f64,
    #[serde(rename = "type")]
    pub type_field: crate::models::GetV1VideoProjectsIdResponseTypeEnum,
    pub width: f64,
}
