/// Generated by Sideko (sideko.dev)
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct GetV1VideoProjectsIdResponse404 {
    pub message: crate::models::GetV1VideoProjectsIdResponse404MessageEnum,
}
