/// Generated by Sideko (sideko.dev)
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct GetV1ImageProjectsIdResponse404 {
    pub message: crate::models::GetV1ImageProjectsIdResponse404MessageEnum,
}
