/// Generated by Sideko (sideko.dev)
/// The request is not properly authenticated
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct GetV1VideoProjectsIdResponse401 {
    pub message: crate::models::GetV1VideoProjectsIdResponse401MessageEnum,
}
