/// Generated by Sideko (sideko.dev)
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct GetV1ImageProjectsIdResponse {
    pub created_at: String,
    pub downloads: Vec<crate::models::GetV1ImageProjectsIdResponseDownloadsItem>,
    pub id: String,
    pub image_count: f64,
    #[serde(deserialize_with = "crate::core::patch::deserialize_required_nullable")]
    pub name: Option<String>,
    pub status: crate::models::GetV1ImageProjectsIdResponseStatusEnum,
    pub total_frame_cost: f64,
    #[serde(rename = "type")]
    pub type_field: crate::models::GetV1ImageProjectsIdResponseTypeEnum,
}
