/// Generated by Sideko (sideko.dev)
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct GetV1ImageProjectsIdResponse401 {
    pub message: crate::models::GetV1ImageProjectsIdResponse401MessageEnum,
}
