/// Generated by Sideko (sideko.dev)
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct PostV1FaceSwapPhotoBodyAssets {
    pub source_file_path: String,
    pub target_file_path: String,
}
