/// Generated by Sideko (sideko.dev)
/// PostV1FilesUploadUrlsResponseItemsItem
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct PostV1FilesUploadUrlsResponseItemsItem {
    pub expires_at: String,
    pub file_path: String,
    pub upload_url: String,
}
