/// Generated by Sideko (sideko.dev)
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct PostV1FaceSwapBodyAssets {
    pub image_file_path: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_file_path: Option<String>,
    pub video_source: crate::models::PostV1FaceSwapBodyAssetsVideoSourceEnum,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub youtube_url: Option<String>,
}
