/// Generated by Sideko (sideko.dev)
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct PostV1VideoToVideoBody {
    pub assets: crate::models::PostV1VideoToVideoBodyAssets,
    pub end_seconds: f64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fps_resolution: Option<crate::models::PostV1VideoToVideoBodyFpsResolutionEnum>,
    pub height: f64,
    #[serde(deserialize_with = "crate::core::patch::deserialize_required_nullable")]
    pub name: Option<String>,
    pub start_seconds: f64,
    pub style: crate::models::PostV1VideoToVideoBodyStyle,
    pub width: f64,
}
