/// Generated by Sideko (sideko.dev)
/// Unprocessable Entity
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct PostV1AiImageGeneratorResponse422 {
    pub message: String,
}
