/// Generated by Sideko (sideko.dev)
/// PostV1ImageBackgroundRemoverBody
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct PostV1ImageBackgroundRemoverBody {
    /// Provide the assets for background removal
    pub assets: crate::models::PostV1ImageBackgroundRemoverBodyAssets,
    /// The name of image
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}
