/// Generated by Sideko (sideko.dev)
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct PostV1AiImageUpscalerBody {
    pub assets: crate::models::PostV1AiImageUpscalerBodyAssets,
    #[serde(deserialize_with = "crate::core::patch::deserialize_required_nullable")]
    pub name: Option<String>,
    pub scale_factor: f64,
    pub style: crate::models::PostV1AiImageUpscalerBodyStyle,
}
