/// Generated by Sideko (sideko.dev)
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct PostV1TextToVideoBody {
    pub end_seconds: f64,
    #[serde(deserialize_with = "crate::core::patch::deserialize_required_nullable")]
    pub name: Option<String>,
    pub orientation: crate::models::PostV1TextToVideoBodyOrientationEnum,
    pub style: crate::models::PostV1TextToVideoBodyStyle,
}
