/// Generated by Sideko (sideko.dev)
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct PostV1VideoToVideoBodyAssets {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_file_path: Option<String>,
    pub video_source: crate::models::PostV1VideoToVideoBodyAssetsVideoSourceEnum,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub youtube_url: Option<String>,
}
