/// Generated by Sideko (sideko.dev)
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct PostV1AiHeadshotGeneratorBody {
    pub assets: crate::models::PostV1AiHeadshotGeneratorBodyAssets,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}
