/// Generated by Sideko (sideko.dev)
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct PostV1TextToVideoBody {
    pub end_seconds: f64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    pub orientation: crate::models::PostV1TextToVideoBodyOrientationEnum,
    pub style: crate::models::PostV1TextToVideoBodyStyle,
}
