/// Generated by Sideko (sideko.dev)
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub enum PostV1VideoToVideoBodyFpsResolutionEnum {
    #[default]
    #[serde(rename = "FULL")]
    Full,
    #[serde(rename = "HALF")]
    Half,
}
impl std::fmt::Display for PostV1VideoToVideoBodyFpsResolutionEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let str_val = match self {
            PostV1VideoToVideoBodyFpsResolutionEnum::Full => "FULL",
            PostV1VideoToVideoBodyFpsResolutionEnum::Half => "HALF",
        };
        write!(f, "{}", str_val)
    }
}
