/// Generated by Sideko (sideko.dev)
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct PostV1LipSyncResponse401 {
    pub message: crate::models::PostV1LipSyncResponse401MessageEnum,
}
