/// Generated by Sideko (sideko.dev)
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct PostV1VideoToVideoBodyStyle {
    pub art_style: crate::models::PostV1VideoToVideoBodyStyleArtStyleEnum,
    pub model: crate::models::PostV1VideoToVideoBodyStyleModelEnum,
    #[serde(deserialize_with = "crate::core::patch::deserialize_required_nullable")]
    pub prompt: Option<String>,
    pub prompt_type: crate::models::PostV1VideoToVideoBodyStylePromptTypeEnum,
    pub version: crate::models::PostV1VideoToVideoBodyStyleVersionEnum,
}
