/// Generated by Sideko (sideko.dev)
/// The request is invalid
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct PostV1AnimationResponse400 {
    pub message: String,
}
