/// Generated by Sideko (sideko.dev)
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub enum PostV1VideoToVideoBodyStyleModelEnum {
    #[default]
    #[serde(rename = "Absolute Reality")]
    AbsoluteReality,
    #[serde(rename = "Dreamshaper")]
    Dreamshaper,
    #[serde(rename = "Flat 2D Anime")]
    Flat2dAnime,
    #[serde(rename = "default")]
    Default,
}
impl std::fmt::Display for PostV1VideoToVideoBodyStyleModelEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let str_val = match self {
            PostV1VideoToVideoBodyStyleModelEnum::AbsoluteReality => "Absolute Reality",
            PostV1VideoToVideoBodyStyleModelEnum::Dreamshaper => "Dreamshaper",
            PostV1VideoToVideoBodyStyleModelEnum::Flat2dAnime => "Flat 2D Anime",
            PostV1VideoToVideoBodyStyleModelEnum::Default => "default",
        };
        write!(f, "{}", str_val)
    }
}
