/// Generated by Sideko (sideko.dev)
/// PostV1VideoToVideoBodyStyleArtStyleEnum
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub enum PostV1VideoToVideoBodyStyleArtStyleEnum {
    #[default]
    #[serde(rename = "3D Render")]
    _3dRender,
    #[serde(rename = "Airbender")]
    Airbender,
    #[serde(rename = "Android")]
    Android,
    #[serde(rename = "Anime Warrior")]
    AnimeWarrior,
    #[serde(rename = "Armored Knight")]
    ArmoredKnight,
    #[serde(rename = "Assassin's Creed")]
    AssassinsCreed,
    #[serde(rename = "Avatar")]
    Avatar,
    #[serde(rename = "Black Spiderman")]
    BlackSpiderman,
    #[serde(rename = "Boba Fett")]
    BobaFett,
    #[serde(rename = "Celestial Skin")]
    CelestialSkin,
    #[serde(rename = "Clay")]
    Clay,
    #[serde(rename = "Comic")]
    Comic,
    #[serde(rename = "Cyberpunk")]
    Cyberpunk,
    #[serde(rename = "Cypher")]
    Cypher,
    #[serde(rename = "Dark Fantasy")]
    DarkFantasy,
    #[serde(rename = "Dragonball Z")]
    DragonballZ,
    #[serde(rename = "Future Bot")]
    FutureBot,
    #[serde(rename = "Futuristic Fantasy")]
    FuturisticFantasy,
    #[serde(rename = "GTA")]
    Gta,
    #[serde(rename = "Ghost")]
    Ghost,
    #[serde(rename = "Gundam")]
    Gundam,
    #[serde(rename = "Hologram")]
    Hologram,
    #[serde(rename = "Illustration")]
    Illustration,
    #[serde(rename = "Impressionism")]
    Impressionism,
    #[serde(rename = "Ink")]
    Ink,
    #[serde(rename = "Ink Poster")]
    InkPoster,
    #[serde(rename = "Jinx")]
    Jinx,
    #[serde(rename = "Knight")]
    Knight,
    #[serde(rename = "Lego")]
    Lego,
    #[serde(rename = "Link")]
    Link,
    #[serde(rename = "Marble")]
    Marble,
    #[serde(rename = "Master Chief")]
    MasterChief,
    #[serde(rename = "Mech")]
    Mech,
    #[serde(rename = "Minecraft")]
    Minecraft,
    #[serde(rename = "Naruto")]
    Naruto,
    #[serde(rename = "Neon Dream")]
    NeonDream,
    #[serde(rename = "Oil Painting")]
    OilPainting,
    #[serde(rename = "On Fire")]
    OnFire,
    #[serde(rename = "Origami")]
    Origami,
    #[serde(rename = "Pixel")]
    Pixel,
    #[serde(rename = "Power Armor")]
    PowerArmor,
    #[serde(rename = "Power Ranger")]
    PowerRanger,
    #[serde(rename = "Retro Anime")]
    RetroAnime,
    #[serde(rename = "Retro Sci-Fi")]
    RetroSciFi,
    #[serde(rename = "Samurai")]
    Samurai,
    #[serde(rename = "Samurai Bot")]
    SamuraiBot,
    #[serde(rename = "Solid Snake")]
    SolidSnake,
    #[serde(rename = "Spartan")]
    Spartan,
    #[serde(rename = "Starfield")]
    Starfield,
    #[serde(rename = "Street Fighter")]
    StreetFighter,
    #[serde(rename = "Studio Ghibli")]
    StudioGhibli,
    #[serde(rename = "Sub-Zero")]
    SubZero,
    #[serde(rename = "The Void")]
    TheVoid,
    #[serde(rename = "Underwater")]
    Underwater,
    #[serde(rename = "Van Gogh")]
    VanGogh,
    #[serde(rename = "Viking")]
    Viking,
    #[serde(rename = "Watercolor")]
    Watercolor,
    #[serde(rename = "Wu Kong")]
    WuKong,
    #[serde(rename = "Zelda")]
    Zelda,
}
impl std::fmt::Display for PostV1VideoToVideoBodyStyleArtStyleEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let str_val = match self {
            PostV1VideoToVideoBodyStyleArtStyleEnum::_3dRender => "3D Render",
            PostV1VideoToVideoBodyStyleArtStyleEnum::Airbender => "Airbender",
            PostV1VideoToVideoBodyStyleArtStyleEnum::Android => "Android",
            PostV1VideoToVideoBodyStyleArtStyleEnum::AnimeWarrior => "Anime Warrior",
            PostV1VideoToVideoBodyStyleArtStyleEnum::ArmoredKnight => "Armored Knight",
            PostV1VideoToVideoBodyStyleArtStyleEnum::AssassinsCreed => "Assassin's Creed",
            PostV1VideoToVideoBodyStyleArtStyleEnum::Avatar => "Avatar",
            PostV1VideoToVideoBodyStyleArtStyleEnum::BlackSpiderman => "Black Spiderman",
            PostV1VideoToVideoBodyStyleArtStyleEnum::BobaFett => "Boba Fett",
            PostV1VideoToVideoBodyStyleArtStyleEnum::CelestialSkin => "Celestial Skin",
            PostV1VideoToVideoBodyStyleArtStyleEnum::Clay => "Clay",
            PostV1VideoToVideoBodyStyleArtStyleEnum::Comic => "Comic",
            PostV1VideoToVideoBodyStyleArtStyleEnum::Cyberpunk => "Cyberpunk",
            PostV1VideoToVideoBodyStyleArtStyleEnum::Cypher => "Cypher",
            PostV1VideoToVideoBodyStyleArtStyleEnum::DarkFantasy => "Dark Fantasy",
            PostV1VideoToVideoBodyStyleArtStyleEnum::DragonballZ => "Dragonball Z",
            PostV1VideoToVideoBodyStyleArtStyleEnum::FutureBot => "Future Bot",
            PostV1VideoToVideoBodyStyleArtStyleEnum::FuturisticFantasy => {
                "Futuristic Fantasy"
            }
            PostV1VideoToVideoBodyStyleArtStyleEnum::Gta => "GTA",
            PostV1VideoToVideoBodyStyleArtStyleEnum::Ghost => "Ghost",
            PostV1VideoToVideoBodyStyleArtStyleEnum::Gundam => "Gundam",
            PostV1VideoToVideoBodyStyleArtStyleEnum::Hologram => "Hologram",
            PostV1VideoToVideoBodyStyleArtStyleEnum::Illustration => "Illustration",
            PostV1VideoToVideoBodyStyleArtStyleEnum::Impressionism => "Impressionism",
            PostV1VideoToVideoBodyStyleArtStyleEnum::Ink => "Ink",
            PostV1VideoToVideoBodyStyleArtStyleEnum::InkPoster => "Ink Poster",
            PostV1VideoToVideoBodyStyleArtStyleEnum::Jinx => "Jinx",
            PostV1VideoToVideoBodyStyleArtStyleEnum::Knight => "Knight",
            PostV1VideoToVideoBodyStyleArtStyleEnum::Lego => "Lego",
            PostV1VideoToVideoBodyStyleArtStyleEnum::Link => "Link",
            PostV1VideoToVideoBodyStyleArtStyleEnum::Marble => "Marble",
            PostV1VideoToVideoBodyStyleArtStyleEnum::MasterChief => "Master Chief",
            PostV1VideoToVideoBodyStyleArtStyleEnum::Mech => "Mech",
            PostV1VideoToVideoBodyStyleArtStyleEnum::Minecraft => "Minecraft",
            PostV1VideoToVideoBodyStyleArtStyleEnum::Naruto => "Naruto",
            PostV1VideoToVideoBodyStyleArtStyleEnum::NeonDream => "Neon Dream",
            PostV1VideoToVideoBodyStyleArtStyleEnum::OilPainting => "Oil Painting",
            PostV1VideoToVideoBodyStyleArtStyleEnum::OnFire => "On Fire",
            PostV1VideoToVideoBodyStyleArtStyleEnum::Origami => "Origami",
            PostV1VideoToVideoBodyStyleArtStyleEnum::Pixel => "Pixel",
            PostV1VideoToVideoBodyStyleArtStyleEnum::PowerArmor => "Power Armor",
            PostV1VideoToVideoBodyStyleArtStyleEnum::PowerRanger => "Power Ranger",
            PostV1VideoToVideoBodyStyleArtStyleEnum::RetroAnime => "Retro Anime",
            PostV1VideoToVideoBodyStyleArtStyleEnum::RetroSciFi => "Retro Sci-Fi",
            PostV1VideoToVideoBodyStyleArtStyleEnum::Samurai => "Samurai",
            PostV1VideoToVideoBodyStyleArtStyleEnum::SamuraiBot => "Samurai Bot",
            PostV1VideoToVideoBodyStyleArtStyleEnum::SolidSnake => "Solid Snake",
            PostV1VideoToVideoBodyStyleArtStyleEnum::Spartan => "Spartan",
            PostV1VideoToVideoBodyStyleArtStyleEnum::Starfield => "Starfield",
            PostV1VideoToVideoBodyStyleArtStyleEnum::StreetFighter => "Street Fighter",
            PostV1VideoToVideoBodyStyleArtStyleEnum::StudioGhibli => "Studio Ghibli",
            PostV1VideoToVideoBodyStyleArtStyleEnum::SubZero => "Sub-Zero",
            PostV1VideoToVideoBodyStyleArtStyleEnum::TheVoid => "The Void",
            PostV1VideoToVideoBodyStyleArtStyleEnum::Underwater => "Underwater",
            PostV1VideoToVideoBodyStyleArtStyleEnum::VanGogh => "Van Gogh",
            PostV1VideoToVideoBodyStyleArtStyleEnum::Viking => "Viking",
            PostV1VideoToVideoBodyStyleArtStyleEnum::Watercolor => "Watercolor",
            PostV1VideoToVideoBodyStyleArtStyleEnum::WuKong => "Wu Kong",
            PostV1VideoToVideoBodyStyleArtStyleEnum::Zelda => "Zelda",
        };
        write!(f, "{}", str_val)
    }
}
