/// Generated by Sideko (sideko.dev)
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct PostV1LipSyncBody {
    pub assets: crate::models::PostV1LipSyncBodyAssets,
    pub end_seconds: f64,
    pub height: f64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    pub start_seconds: f64,
    pub width: f64,
}
