/// Generated by Sideko (sideko.dev)
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct PostV1FilesUploadUrlsBodyItemsItem {
    pub extension: String,
    #[serde(rename = "type")]
    pub type_field: crate::models::PostV1FilesUploadUrlsBodyItemsItemTypeEnum,
}
