/// Generated by Sideko (sideko.dev)
#[derive(Clone, Debug)]
pub struct FilesClient {
    base_client: crate::core::base_client::BaseClient,
}
impl FilesClient {
    pub(crate) fn new(base_client: crate::core::base_client::BaseClient) -> Self {
        Self { base_client }
    }
    pub fn upload_urls(
        &self,
    ) -> crate::resources::v1::files::upload_urls::resource_client::UploadUrlsClient {
        crate::resources::v1::files::upload_urls::resource_client::UploadUrlsClient::new(
            self.base_client.clone(),
        )
    }
}
