/// Generated by Sideko (sideko.dev)
#[derive(Clone, Debug)]
pub struct AiHeadshotGeneratorClient {
    base_client: crate::core::base_client::BaseClient,
}
impl AiHeadshotGeneratorClient {
    pub(crate) fn new(base_client: crate::core::base_client::BaseClient) -> Self {
        Self { base_client }
    }
    /// Create an AI headshot. Each headshot costs 50 frames.
    ///
    /// POST /v1/ai-headshot-generator
    pub async fn create(
        &self,
        request: super::request_types::CreateRequest,
    ) -> crate::SdkResult<crate::models::PostV1AiHeadshotGeneratorResponse> {
        let url = self.base_client.build_url("/v1/ai-headshot-generator");
        let mut builder = reqwest::Client::default().post(&url);
        builder = builder.header("x-sideko-sdk-language", "rust");
        builder = builder.header("content-type", "application/json");
        builder = builder
            .json(
                &crate::models::PostV1AiHeadshotGeneratorBody {
                    name: request.name,
                    assets: request.assets,
                },
            );
        builder = self.base_client.apply_auths_to_builder(builder, &["bearerAuth"]);
        let mut response = builder.send().await?;
        response = self.base_client.error_for_status(response).await?;
        crate::core::response::process_json::<
            crate::models::PostV1AiHeadshotGeneratorResponse,
        >(response)
            .await
    }
}
