# This workflow will publish the rust package to crates.io on release
# or manual trigger
#
# REQUIREMENTS:
#   - Define a secret `CRATES_IO_TOKEN` in your github environment
#   - Define a secret `SIDEKO_API_KEY` in your github environment
#
# MAINTENANCE:
#   - Workflow triggers `on: ...` can be edited and Sideko will maintain the `jobs: ...`
#   - Alternatively, if you wish to fully customize the workflow, you can clone this
#     file (save under a different filepath to avoid clashing) and either disable this workflow
#     via the triggers or remove `github` from the `ci_cd` options in the SDK config.
#
name: Publish to crates.io

on:
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      #---------------------------------------------------
      #  -----  checkout & setup rust toolchain  -----
      #---------------------------------------------------
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      #---------------------------------------
      #  -----  publish to crates.io -----
      #---------------------------------------
      - name: publish
        run: cargo publish --token ${{ secrets.CRATES_IO_API_TOKEN }}
      #----------------------------------------------
      #  -----  mark SDK as released in Sideko  -----
      #----------------------------------------------
      - name: install sideko cli
        run: npm install -g @sideko/cli
      - name: mark sdk as released
        env:
          SIDEKO_API_KEY: ${{ secrets.SIDEKO_API_KEY }}
        run: sideko sdk released
