# This workflow will test the rust package against Sideko's Mock Servers
# Tests will run automatically on a push to `main` or a pull request event

name: Run Tests

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust_version:
          - "1.60"
          - "1.70"
          - "1.80"
          - "1.90"
          - "stable"
    steps:
      #---------------------------------------------------
      #  -----  checkout & setup rust toolchain  -----
      #---------------------------------------------------
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust_version }}
      #---------------------------------------------------
      #  -----  install dependencies & run tests -----
      #---------------------------------------------------
      - name: run tests
        run: cargo test --no-fail-fast
