# This workflow will test the rust package against Sideko's Mock Servers
# Tests will run automatically on a push to `main` or a pull request event

name: Run Tests

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    strategy:
      fail-fast: false
      matrix:
        rust_version:
          - "1.90.0"
          - "1.95.0"
          - "stable"
    steps:
      #---------------------------------------------------
      #  -----  checkout & setup rust toolchain  -----
      #---------------------------------------------------
      - name: checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: setup rust
        uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17
        with:
          toolchain: ${{ matrix.rust_version }}
      #---------------------------------------------------
      #  -----  install dependencies & run tests -----
      #---------------------------------------------------
      - name: run tests
        run: cargo test --no-fail-fast
